### ISSUE TITLE
Can´t make the plugin work

### ISSUE THREAD

**Issue by marcelbonfim182** [bradmartin/nativescript-image-filters#11]
Hi,
I am using the plugin with pure javascript, for me, the coding I put is correct, however when opening the app, it shows error, the console opens and shows the following message: com.mukesh.image_processing.ImageProcessor is not a constructor. Can somebody help me?

My code:

`var topmost = require("tns-core-modules/ui/frame").topmost;
var Image = require("tns-core-modules/ui/image").Image;
var Observable = require("tns-core-modules/data/observable").Observable;
var ImageFilters = require("nativescript-image-filters").ImageFilters;
var filter = new ImageFilters();

function invertimage(args) {
     var pic = topmost().currentPage.getViewById('myPicture');
					  
     filter.invert(pic).then(function (result) {
	 pic.imageSource = result;
     }).catch(function (err) {
          console.log('applyFilter ERROR: ' + err);
     });
}
exports.invertimage = invertimage;
`

**Comment by bradmartin** [comment]
Build issue. Be sure to clean your project. This adds a native dependency which requires a complete Android build to occur.

Simply put, delete platforms directory and build the app again. Then you'll have the native lib compiled into your project.

**Comment by marcelbonfim182** [comment]
It worked!! Thanks!!!
