### ISSUE TITLE
Project status update

### ISSUE THREAD

**Issue by Aceman18** [bradmartin/nativescript-image-filters#14]
Hi there,

I Understand you are a busy person with other plugins to keep up but I was wondering what the status with this one is?

I notice it's been over a year since updates even though the package is getting plenty of downloads today.

You mention the package hasn't been fully tested / cleaned up and some of the filters are not named correctly. Will this be done?

**Comment by bradmartin** [comment]
The package should still be working. What I meant by `You mention the package hasn't been fully tested / cleaned up and some of the filters are not named correctly. ` Was that I didn't go and confirm all the filters across iOS/android to ensure they're named correctly in a 1 to 1 fashion.

If you would like to help contribute that would be very appreciated, but again, not totally necessary as the plugin seems to still be working correctly. If you encounter and issues I'd be happy to help you figure it out 😄

**Comment by Aceman18** [comment]
Ok thats fine Brad thank you. 
I just wanted this information as I am evaluating whether I can use this for a project or not.

Much appreciated I will close this now.
