### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jmrapp1** [bradmartin/nativescript-image-filters#2]
It may help others by providing instructions on how to install this. More specifically: the need to go into the module folder of `nativescript-image-filters` and run `npm install`

**Comment by bradmartin** [comment]
In your own project the cmd is on the README here: https://github.com/bradmartin/nativescript-image-filters#installation so you shouldn't have to do that unless you have a different setup than the default NS app structure. If you're having any issue with the `tns plugin add` cmd let me know 👍
