### ISSUE TITLE
Cant set watermark

### ISSUE THREAD

**Issue by jbejas** [bradmartin/nativescript-image-filters#3]
Im having trouble setting a watermark over an image. This is my code.

marcadeagua() {
    setTimeout(() => {
      const img = topmost().getViewById("imageOne") as Image;
      this.punto = new android.graphics.Point(0,0)
      this.filtros.waterMark(img,"~/images/bart.png",this.punto,1,1,1,false).then(
        result => {
          img.imageSource = result;
        },
        err => {
          console.log("applyFilter ERROR: " + err);
        }
      );
    }, 150);
  }

Is there something im missing here?

**Comment by bradmartin** [comment]
🤔 that looks okay to me, I'll try a test on it later. If you find the solution before let me know.

**Comment by bradmartin** [comment]
Use this to get started:

``` typescript
 const punto = new android.graphics.Point(50, 40);
      console.log("punto", punto);
      const androidColor = new Color("#ff4801").android;
      this._ImageFilters
        .waterMark(img, "Hello Testing", punto, androidColor, 500, 40, true)
        .then(
          result => {
            console.log(result);
            img.imageSource = result;
          },
          err => {
            console.log("applyFilter ERROR: " + err);
          }
        );
```
It is working fine with those values for the arguments.

**Comment by jbejas** [comment]
You are the man! I just thought that i could use another image as Watermark. Is there any way to do that? Thanks!

**Comment by bradmartin** [comment]
Not that I know of. The native android method is actually drawing the `string` you pass onto the image at the position. Like a watermark would normally work I suppose in most image editors, although I won't claim to be an expert on that 😄.
