### ISSUE TITLE
Problem when build application

### ISSUE THREAD

**Issue by luisibanhi** [bradmartin/nativescript-image-filters#4]
When i trying build application, this problems was happened on my console.

../nativescript-image-filters/index.d.ts(1,22): error TS6053: File '/Users/luisibanhi/Projetos/CasaCafe/casaecafe-app/node_modules/nativescript-image-filters/node_modules/tns-platform-declarations/android.d.ts' not found.
../nativescript-image-filters/index.d.ts(50,15): error TS2503: Cannot find namespace 'android'.
──────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.4.0           │ 3.4.1          │ Update available │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date       │
│ tns-android      │ 3.4.0           │ 3.4.1          │ Update available │
│ tns-ios          │ 3.4.0           │ 3.4.1          │ Update available │
└──────────────────┴──────

**Comment by andreassimon** [comment]
Same here

**Comment by bradmartin** [comment]
One possible solution to avoid this is to tell the TS compiler to not look into node_modules as you should not be modifying or processing anything in node_modules.

Can you make sure your project's `tsconfig.json` has the `exclude` array with `"node_modules" listed? This should tell the compiler to not look into node_modules. Also, we can just drop it from the `index.d.ts` for this module :)

http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by bradmartin** [comment]
Pub'd 2.0.1 - LMK if it helps

**Comment by andreassimon** [comment]
Unfortunately, it does not help:
```
$ npm update
+ nativescript-image-filters@2.0.1
updated 1 package in 0.587s

$ tns debug android
Searching for devices...
Executing before-prepare hook from .../hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.6.2
node_modules/nativescript-image-filters/index.d.ts(49,15): error TS2503: Cannot find namespace 'android'.

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 1.
Executing after-watch hook from .../hooks/after-watch/nativescript-dev-typescript.js
```

What about moving `"tns-platform-declarations": "^3.0.0"` from `devDependencies` to `dependencies`?
