### ISSUE TITLE
Error when working with http images

### ISSUE THREAD

**Issue by altinselimi** [bradmartin/nativescript-image-filters#5]
Hi, I'm trying to do a gaussianBlur effect on an image. I am using nativecript-vue so maybe this information is useful.

The code looks like this:

```
<template>
	<Image column="0" v-if="image" :ref="'target' + id" :src="image" stretch="aspectFit" />
</template>
<script>
mounted() {
	if (this.image) {
		let pic = this.$refs['target' + this.id].nativeView; // nativeView
		filters.gaussianBlur(pic, 100).then((result) => {
			pic.imageSource = result;
		}).catch((err) => {
			console.log('applyFilter ERROR: ' + err);
		});
	}
}
</script>
```

This code throws error:
`applyFilter ERROR: TypeError: null is not an object (evaluating \'e.ios.image.CGImage\')`

But if I put that code inside setTimeout, it works perfectly, like so:
```
setTimeout(() => {
	let pic = this.$refs['target' + this.id].nativeView; // nativeView
	filters.gaussianBlur(pic, 100).then((result) => {
		pic.imageSource = result;
	}).catch((err) => {
		console.log('applyFilter ERROR: ' + err);
	});
}, 1000);
```

What could be the problem and how may I resolve it ?

**Comment by bradmartin** [comment]
My initial guess with a remote image is that it's not loaded when the logic runs. Hence the timeout fixing it.
