### ISSUE TITLE
Rotate does not rotate

### ISSUE THREAD

**Issue by mariano-aguero** [bradmartin/nativescript-image-filters#9]
the "rotate" method applies a contrast on the image, I think the method should be called in another way since it confuses and it is expected that the image can be rotated

**Comment by carrbrpoa** [comment]
Release for that? :)

**Comment by bradmartin** [comment]
I think you might be running older gradle for your builds, `implementation` is newer, not sure on all the specifics there but I ran the demo before latest release which fixed this and improved the bitmap conversion.
